name: MacOS Make

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make main
    - name: check and rename
      run: |
        cp main Zff-macOS-x86_64
        ls
      # tag 查询github-Release
      # 上传artifacts          
    - uses: actions/upload-artifact@v3
      with:
        name: Zff-macOS-x86_64
        path: |
          main
          usr/
    - name: zip
      run: |
        zip -vr mac.zip Zff-macOS-x86_64 usr LICENCE README.md -x "*.DS_Store"
    # tag 上传Release
    - name: uploadRelease
      if: startsWith(github.event.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mac.zip
        asset_name: Zff-macOS-x86_64.zip
        tag: ${{ github.ref }}
        overwrite: true
