name: MacOS Make

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make main
    - name: check
      run: ls
      # tag 查询github-Release
      # 上传artifacts          
    - uses: actions/upload-artifact@v3
      with:
        name: Zff-macOS-x86_64
        path: |
          main
          usr/
    # tag 上传Release
    - name: uploadRelease
      if: startsWith(github.event.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: main
        asset_name: Zff-macOS-x86_64
        tag: ${{ github.ref }}
        overwrite: true
