name: Ubuntu Make

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make zff_main_en
    - name: check
      run: ls
      # tag 查询github-Release
      # 上传artifacts          
    - uses: actions/upload-artifact@v2
      with:
        name: Zff-Ubuntu
        path: zff_main_en
    # tag 上传Release
    - name: uploadRelease
      if: startsWith(github.event.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: zff_main_en
        asset_name: Zff-Ubuntu
        tag: ${{ github.ref }}
        overwrite: true
