name: Ubuntu Make

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: gcc
      run: g++ ./main.cpp -o main -pthread
    - name: check
      run: ls
      # tag 查询github-Release
      # 上传artifacts          
    - uses: actions/upload-artifact@v3
      with:
        name: Zff-Ubuntu
        path: |
          main
          usr/
    # tag 上传Release
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r data.zip usr
    - name: uploadRelease
      if: startsWith(github.event.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: main
        asset_name: Zff-Ubuntu
        tag: ${{ github.ref }}
        overwrite: true
    - name: upload Release (usr/ data)
      if: startsWith(github.event.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: data.zip
        asset_name: data.zip
        tag: ${{ github.ref }}
        overwrite: true