name: Windows x64 MSVC Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        id: setup
        with:
          platform: x64
      - name: Build something requiring CL.EXE
        run: |
          ${{ steps.setup.outputs.gxx }} main.cpp -o main.exe -std=c++11 -static-libgcc -static-libstdc++ -L.
      # Runs a single command using the runners shell
      - name: Check file
        run: |
          copy main.exe Zff-Windows-x86_64.exe
          dir
      # tag 查询github-Release
      # 上传artifacts          
      - uses: actions/upload-artifact@v3
        with:
          name: Zff-Windows-x86_64.exe
          path: |
            main.exe
            usr/
      - uses: edgarrc/action-7z@v1
        with:
          args: 7z a win64.zip Zff-Windows-x86_64.exe usr LICENCE README.md
      # tag 上传Release
      - name: upload Release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: win64.zip
          asset_name: Zff-Windows-x86_64.zip
          tag: ${{ github.ref }}
          overwrite: true

